version: '3.9'

services:
  db:
    container_name: postgres
    image: postgres:13-alpine
    env_file:
      - ./postgres_elastic_etl/envs/db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  es:
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
  etl:
    container_name: etl
    image: etl:v2.0
    build:
      context: .
      dockerfile: postgres_elastic_etl/docker/Dockerfile
    env_file:
      - ./postgres_elastic_etl/envs/etl.env
    volumes:
      - etl_state:/usr/src/code/postgres_elastic_etl/data/
volumes:
  postgres_data:
  elastic_data:
  etl_state:
